apiVersion: v1
appVersion: 1.0.0
description: Fission is a fast serverless framework for Kubernetes.
engine: gotpl
home: http://fission.io/
keywords:
- fission
- serverless
maintainers:
- email: soamvasani@platform9.com
  name: Soam Vasani
- email: contact@tachingchen.com
  name: Ta Ching Chen
name: fission-all
version: 1.0.0
